# Generated by Django 3.2.16 on 2022-10-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_manage_staff_users', 'Can manage staff user'), ('can_manage_roles', 'Can manage roles'), ('can_manage_cateogries', 'Can manage categories'), ('can_manage_website_Settings', 'Can manage website settings')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
