# Generated by Django 3.2.16 on 2022-10-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_manage_staff_users', 'Can manage staff users'), ('can_manage_simple_users', 'Can manage simple users'), ('can_manage_categories', 'Can manage categories'), ('can_manage_website_settings', 'Can manage website settings')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
