# Generated by Django 3.2.16 on 2022-10-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='name', max_length=128, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nick_name',
            field=models.CharField(default='nick_name', max_length=128, verbose_name='Nick name'),
            preserve_default=False,
        ),
    ]
