# Generated by Django 3.2.16 on 2022-10-30 17:01

import django.core.validators
from django.db import migrations, models
import panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('text', models.TextField(verbose_name='Text')),
                ('email', models.EmailField(blank=True, default='info@site.com', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='+989121231234', max_length=13, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Text')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('name', models.CharField(default='admin panel', max_length=250, verbose_name='Name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='website url')),
                ('logo', models.ImageField(blank=True, default='static/assets/img/brand/logo.png', null=True, upload_to=panel.models.get_logo_path, verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, default='static/assets/img/brand/favcion.ico', null=True, upload_to=panel.models.get_favicon_path, verbose_name='Favicon')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
