# Generated by Django 3.2.16 on 2022-10-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_aboutus_contactus_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='slug',
            field=models.SlugField(default='aboutus', max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='slug',
            field=models.SlugField(default='settings', max_length=250, unique=True, verbose_name='Slug'),
        ),
    ]
