# Generated by Django 3.2.16 on 2022-10-31 08:09

from django.db import migrations, models
import panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_settings_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='favicon',
            field=models.ImageField(blank=True, default='logo/favcion.ico', null=True, upload_to=panel.models.get_favicon_path, verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, default='logo/logo.png', null=True, upload_to=panel.models.get_logo_path, verbose_name='Logo'),
        ),
    ]
