# Generated by Django 3.2.16 on 2022-10-31 08:11

from django.db import migrations, models
import panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20221031_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='favicon',
            field=models.ImageField(blank=True, default='logo/favicon.ico', null=True, upload_to=panel.models.get_favicon_path, verbose_name='Favicon'),
        ),
    ]
