# Generated by Django 3.2.16 on 2022-10-31 16:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_settings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='terms',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Terms and Conditions'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
